#S3 BUCKETS CONFIG (KEY_ID, SECRET_KEY, SHOULD ALL BE HIDDEN! )
AWS_ACCESS_KEY_ID = 'AKIAZHCVDPUKBB2LK6WD'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'django-greensky-bucket'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATICFILES_STORAGE = '{project4}.storages.backends.s3boto3.S3Boto3Storage'

## different
AWS_LOCATION = 'static'